Project/Project/apps/Calendar/urls.py
from django.conf.urls import url
from . import views

app_name = "Calendar"
urlpatterns = [
	url(r'^calendar/$', views.CalendarView.as_view(), name = 'calendar'),
	url(r'^event/new/$', views.new_event, name='event_new'),
	url(r'^event/details/(?P<event_id>\d+)/$', views.details, name='details'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.edit_event, name='edit_event'),
	url(r'^event/delete/(?P<event_id>\d+)/$', views.delete_event, name='delete_event'),
	url(r'^event/status/(?P<event_id>\d+)/$', views.status_change, name='change_status'),
]

Project/Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Calendar.urls')),
]

Project/Project/apps/Calendar/models.py
from django.db import models
from django.urls import reverse
from datetime import *

class Event(models.Model):
	title = models.CharField(max_length = 200)
	description = models.TextField()
	start_time = models.DateTimeField()
	end_time = models.DateTimeField()
	status = models.BooleanField(default=False)

	#Функция возвращает оставшееся время до конца ивента
	def TimeRemains(self):
		remaining_time = self.end_time - datetime.now(timezone.utc)
		expire_check = self.end_time
		#Проверка кол-ва секунд между датой конца события и текущей датой
		if remaining_time.total_seconds() < 0:
			return 'Event expired!'
		return remaining_time

	@property
	def get_html_url(self):
		url = reverse('Calendar:details', args=(self.id,))
		if self.status == False:
			return f'<a href="{url}" style="color:red;"> {self.title} </a>'
		else:
			return f'<a href="{url}" style="color:green;"> {self.title} </a>'

Project/Project/apps/Calendar/forms.py
from django.forms import ModelForm, DateInput

from .models import Event

class EventForm(ModelForm):
  class Meta:
    model = Event
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = ['title','description','start_time','end_time']

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

Project/Project/apps/Calendar/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar

from .models import *
from .utils import Calendar
from .forms import EventForm


class CalendarView(generic.ListView):
	model = Event
	template_name = 'Calendar/calendar.html'

	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		date = get_date(self.request.GET.get('month', None))

		cal = Calendar(date.year, date.month)

		html_cal = cal.formatmonth(withyear=True)
		context['calendar'] = mark_safe(html_cal)

		date = get_date(self.request.GET.get('month', None))
		context['prev_month'] = prev_month(date)
		context['next_month'] = next_month(date)
		return context




def get_date(required_month):
	if required_month:
		year, month = (int(x) for x in required_month.split('-'))
		return date(year, month, day = 1)
	return datetime.today()


def prev_month(current_month):
	first = current_month.replace(day=1)
	prev_month = first - timedelta(days=1)
	month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
	return month


def next_month(current_month):
	days_in_month = calendar.monthrange(current_month.year, current_month.month)[1]
	last = current_month.replace(day=days_in_month)
	next_month = last + timedelta(days=1)
	month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
	return month


def details(request, event_id):
 	choosenEvent = Event.objects.get(id = event_id)
 	return render(request, 'Calendar/details.html', {'choosenEvent':choosenEvent})


def new_event(request):
    instance = Event()
    
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('Calendar:calendar'))
    return render(request, 'Calendar/event.html', {'form': form})


def edit_event(request, event_id=None):
	instance = Event()
	if event_id:
		instance = get_object_or_404(Event, pk=event_id)
	form = EventForm(request.POST or None, instance=instance)
	if request.POST and form.is_valid():
		form.save()
		return HttpResponseRedirect(reverse('Calendar:details', args=(event_id,)))
	return render(request, 'Calendar/event.html', {'form':form})

def delete_event(request, event_id):
	event_to_delete = Event.objects.get(id = event_id)
	event_to_delete.delete()
	return HttpResponseRedirect(reverse('Calendar:calendar'))

def status_change(request, event_id):
	event = Event.objects.get(id = event_id)
	event.status = True;
	event.save()
	return HttpResponseRedirect(reverse('Calendar:calendar'))

Project/Project/templates/Calendar/calendar.html
{% extends 'base.html' %}

{% block styles %}{% endblock %}

{% block title %}
<div class="PageTitle">Calendar</div>
{% endblock %}

{% block content %}

<div class="clearfix">
	<a class="btn left month-button" href="{% url 'Calendar:calendar'  %}?{{ prev_month }}"> < </a>
	<a class="btn right month-button" href="{% url 'Calendar:calendar' %}?{{ next_month }}"> > </a>
	<a class="btn right" href="{% url 'Calendar:event_new' %}"> New Event </a>
</div>
<div class="coverColor"></div>
<div class="coverColor2"></div>

{{ calendar }}

{% endblock %}

Project/Project/templates/Calendar/details.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'assets/css/details.css' %}">
{% endblock %}

{% block title %}
<div class="PageTitle">Details</div>
{% endblock %}

{% block content %}

<div class="clearfix">
  <a class="btn left" href="{% url 'Calendar:calendar' %}"> Calendar </a>
</div>

<section>
	<p class="display DetailTitle">Name:</p><p class="display DetailContent">{{choosenEvent.title}}</p>
</section>
<br><hr>
<section>
	<p class="display DetailTitle">Description:</p><p class="display DetailContent">{{choosenEvent.description}}</p>
</section>
<br><hr>
<section>
	<p class="display DetailTitle">Start date:</p><p class="display DetailContent">{{choosenEvent.start_time}}</p>
</section>
<br><hr>
<section>
	<p class="display DetailTitle">End before:</p><p class="display DetailContent">{{choosenEvent.end_time}}</p>
</section>
<br><hr>
<section>
	<p class="display DetailTitle">Remaining time:</p><p class="display DetailContent">{{choosenEvent.TimeRemains}}</p>
</section>
<br><hr>
<section>
	{% if choosenEvent.status == False %}
		<p class="display DetailTitle">Status:</p>
		<p class="display DetailContent">Undone</p>
	{% elif choosenEvent.status == True %}
		<p class="display DetailTitle">Status:</p>
		<p class="display DetailContent">Done</p>
	{% endif %}
</section>
<hr>
<div class="detailsMenu">
  <a class="btn detailButton left" href="{% url 'Calendar:edit_event' event_id=choosenEvent.id %}"> Edit </a>
  <a class="btn detailButton left" href="{% url 'Calendar:delete_event' event_id=choosenEvent.id %}"> Delete </a>
  <a class="btn detailButton left" href="{% url 'Calendar:change_status' event_id=choosenEvent.id %}"> Done </a>
{% endblock %}

Project/Project/templates/Calendar/event.html
{% extends 'base.html' %}

{% block styles %}{% endblock %}

{% block title %}
<div class="PageTitle">Event</div>
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn left" href="{% url 'Calendar:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

Project/Project/templates/base.html
<!-- cal/templates/cal/base.html -->

{% load static %}

<!doctype html>

<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  {% block styles %}{% endblock %}
  <title>Django Calendar App</title>
</head>

<body>

  <h1 class="title">{% block title %}{% endblock %}</h1>
  
  {% block content %}

  {% endblock %}



  {% block script %}

  {% endblock %}
</body>
</html>